<!DOCTYPE html>
<html lang="en">
<head>
  <title>IICS E - Services</title>
</head>
<body>
  <center>
    <div>  
      <h4>
        UNIVERSITY OF SANTO TOMAS<br>Institute of Information Computing Sciences
      </h4>
      <label>
        Generated On: {{ $generated_on }}
      </label>
      <br>
      <label>
        Generated By: {{ $fname }} {{ $lname }}
      </label>
      <br><br>
      <h4>
        Request Fulfilled List for Course Crediting
      </h4>
    </div>
  </center>
  <br>
  <table style="font-size: 12px; border-collapse: collapse" border="1">
    <tr>
      <th style="text-align: center">
        Trans. No.
      </th>
      <th style="text-align: center">
        Student No.
      </th>
      <th style="text-align: center">
        Name
      </th>
      <th style="text-align: center">
        Date
      </th>
      <th style="text-align: center">
        Email
      </th>
      <th style="text-align: center">
        Section
      </th>
    </tr>
  </table>
</body>
</html>