<!DOCTYPE html>
<html lang="en">
<head>
  <title>CICS E - Services</title>
</head>
<body>
  <center>
    <div>  
      <h4>
        UNIVERSITY OF SANTO THOMAS<br>College of Information Computing Sciences
      </h4>
      <h4>
        Request Fulfilled List for Student Appeal
      </h4>
    </div>
  </center>
  <br>
  <table style="font-size: 12px; border-collapse: collapse; margin-left: auto; margin-right: auto; width: 100%;" border="1">
    <tr>
      <th style="text-align: center">
        Trans. No.
      </th>
      <th style="text-align: center">
        Student No.
      </th>
      <th style="text-align: center">
        Name
      </th>
      <th style="text-align: center">
        Date
      </th>
      <th style="text-align: center">
        Email
      </th>
      <th style="text-align: center">
        Section
      </th>
      <th style="text-align: center">
        Active Contact No.
      </th>
      <th style="text-align: center">
        Active Email Address
      </th>
    </tr>
    @foreach($appealDetails as $appeal_detail)
      <tr style="text-align: center">
        <td>{{ $appeal_detail->id }}</td>
        <td>{{ $appeal_detail->student_id }}</td>
        <td>{{ $appeal_detail->fname }} {{ $appeal_detail->lname }}</td>
        <td>{{ date("M d, Y", strtotime($appeal_detail->created_at)) }}</td>
        <td>{{ $appeal_detail->email }}</td>
        <td>{{ $appeal_detail->section }}</td>
        <td>{{ $appeal_detail->active_contact_number }}</td>
        <td>{{ $appeal_detail->active_email }}</td>
      </tr>
    @endforeach
  </table>
  <br><br>
  <label>
    Generated On: {{ $generated_on }}
  </label>
  <br>
  <label>
    Generated By: {{ $fname }} {{ $lname }}
  </label>
</body>
</html>