<!DOCTYPE html>
<html lang="en">
<head>
  <title>IICS E - Services</title>
</head>
<body>
  <center>
    <div>  
      <h4>
        UNIVERSITY OF SANTO TOMAS<br>Institute of Information Computing Sciences
      </h4>
      <label>
        Generated On: {{ $generated_on }}
      </label>
      <br>
      <label>
        Generated By: {{ $fname }} {{ $lname }}
      </label>
      <br><br>
      <h4>
        Request Fulfilled List for Course Crediting
      </h4>
    </div>
  </center>
  <br>
  <table style="font-size: 12px; border-collapse: collapse; margin-left: auto; margin-right: auto; width: 100%;" border="1">
    <tr>
      <th style="text-align: center">
        Trans. No.
      </th>
      <th style="text-align: center">
        Student No.
      </th>
      <th style="text-align: center">
        Name
      </th>
      <th style="text-align: center">
        Date
      </th>
      <th style="text-align: center">
        Email
      </th>
      <th style="text-align: center">
        Section
      </th>
    </tr>
    @foreach($creditDetails as $credit_detail)
      <tr style="text-align: center">
        <td>{{ $credit_detail->id }}</td>
        <td>{{ $credit_detail->student_id }}</td>
        <td>{{ $credit_detail->fname }} {{ $credit_detail->lname }}</td>
        <td>{{ date("M d, Y", strtotime('$credit_detail->created_at')) }}</td>
        <td>{{ $credit_detail->email }}</td>
        <td>{{ $credit_detail->section }}</td>
      </tr>
    @endforeach
  </table>
</body>
</html>